name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - run: npm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - run: npm run format:check
